/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],

  content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  safelist: [
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-5',
    'sm:col-span-6',
    'sm:col-span-7',
    'sm:col-span-8',
    'sm:col-span-9',
    'sm:col-span-10',
    'sm:col-span-11',
    'sm:col-span-12',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-5',
    'md:col-span-6',
    'md:col-span-7',
    'md:col-span-8',
    'md:col-span-9',
    'md:col-span-10',
    'md:col-span-11',
    'md:col-span-12',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'lg:col-span-7',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-10',
    'lg:col-span-11',
    'lg:col-span-12',
    'sm:grid-cols-1 ',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'md:grid-cols-1 ',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-1 ',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    screens: {
      vsm: {max: '549px'},
      sm: {max: '679px'},
      planSm: {max: '768px'},
      md: {max: '979px'},
      lg: '980px',
      xl: '1280px',
    },
    maxWidth: {
      1216: '1216px',
      936: '936px',
      728: '728px',
    },
    colors: {
      white: '#fff',
      black: 'black',
      'bg-lite': '#EDF2F6',
      'bg-dark': '#17181C',
      'header-bg-lite': '#101828',
      'header-bg-dark': '#000000',
      'heading-text-lite': '#101828',
      'heading-text-dark': '#F5F5F6',
      'template-item-text-default-lite': '#2D384B',
      'template-item-text-dark': '#CECFD2',
      'template-item-text-active-lite': '#0B3BEC',
      'template-card-item-text-lite': '#475467',
      'template-card-item-text-dark': '#94969C',
      'template-card-item-bg-lite': '#FFFFFF',
      'template-card-item-bg-dark': '#000000',
      'items-border-lite': '#D0D5DD',
      'items-border-dark': '#333741',
      'search-template-input-bg-lite': '#E3EAEF',
      'search-template-input-bg-dark': '#21242C',
      'bg-home-white': 'rgba(237, 242, 246, 1)',
      'active-btn-white': 'rgba(11, 59, 236, 1)',
      'active-text-color-white': 'rgba(255, 255, 255, 1)',
      'text-color-white': 'rgba(152, 162, 179, 1)',
      'black-text': 'rgba(16, 24, 40, 1)',
    },
    boxShadow: {
      'logo-shadow': '10px 0px 8px -2px rgba(11, 59, 236, 0.5)',
      'arrow-r-20-lite': '0px 0px 9px 13px #EDF2F6',
      'arrow-r-20-dark': '0px 0px 9px 13px #17181C',
      'chat-items': '0px 0px 9px 13px #EDF2F6',
    },
    extend: {
      fontFamily: {
        TTNormsMedium: ['TTNormsMedium'],
        NeueMachinaBold: ['NeueMachinaBold'],
        NeueMachinaMedium: ['NeueMachinaMedium'],
        TTNormsRegular: ['TTNormsRegular'],
        InterMedium: ['InterMedium'],
        InterRegular: ['InterRegular'],
        InterBold: ['InterBold'],
        TTNormsBold: ['TTNormsBold'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {height: 0},
          to: {height: 'var(--radix-accordion-content-height)'},
        },
        'accordion-up': {
          from: {height: 'var(--radix-accordion-content-height)'},
          to: {height: 0},
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('tailwindcss-pseudo-elements')],
}
